### ISSUE TITLE
Can't view timetable

### ISSUE THREAD

**Issue by maisieccino** [mbellgb/ucl-assistant#33]
Timetable items do not appear, no error shown.

**Comment by mbellgb** [comment]
Breakage in upstream API. See uclapi/uclapi#641 for progress.

**Comment by maisieccino** [comment]
2017/2018 timetable has been wiped from UCL's timetable system, thus unavailable to UCL API and in turn unavailable to UCL Assistant. This is supposedly intentional behaviour so will mark this as wontfix.

**Comment by maisieccino** [comment]
[More information from UCL API Twitter](https://twitter.com/uclapi/status/1023515116506152960)
